### API Ping
GET http://localhost:3001/ping

### List Opportunities
GET http://localhost:3001/api/v1/opportunity

### Show Opportunity
GET http://localhost:3001/api/v1/opportunity/id

### Create Opportunity
POST http://localhost:3001/api/v1/opportunity
Content-Type: application/json

{
  "role": "Senior Software Engineer",
  "company": "ImperioSoft Studios",
  "location": "Brazil - São Paulo",
  "remote": true,
  "salary": 520000,
  "link": "https://www.linkedin.com/in/andre-dorneles-pereira/"
}

### Update Opportunity
PATCH http://localhost:3001/api/v1/opportunity/id
Content-Type: application/json

{
  "role": "Senior Software Engineer",
  "company": "ImperioSoft Studios",
  "location": "Brazil - São Paulo",
  "remote": true,
  "salary": 520000,
  "link": "https://www.linkedin.com/in/andre-dorneles-pereira/"
}

### Delete Opportunity
DELETE http://localhost:3001/api/v1/opportunity/id
